### ISSUE TITLE
mining blocks HWT video below

### ISSUE THREAD

**Issue by SavexG** [lambda-plugins/HighwayTools#17]
https://youtu.be/OrKzBaawxp0

this happens in both spoof and viewlock with all blocks

**Comment by luxuwu** [comment]
tern on more packets to fix this

**Comment by SavexG** [comment]
oh thanks, Im getting kicked though with nopackets when it hast to mine more then 1 Obsidian

**Comment by Avanatiker** [comment]
Fixed in latest commit please wait for release
