### ISSUE TITLE
only taking 1 stack of obsidian from shulker box

### ISSUE THREAD

**Issue by luxuwu** [lambda-plugins/HighwayTools#18]
it would be so much more efficient if it takes all the obsidian that can fit in your inventory instead of just 1 stack and having to stop to restock every 10 seconds. idk if this is just me. love this plugin btw

**Comment by Avanatiker** [comment]
Thanks for using it :) Thats not intended. Do you use this module with multiple bots?

**Comment by ReadZead** [comment]
I have the same issue where if there's a shulker with obby it takes one stack, mine the shulker, place it back down and then grab another stack, and it keeps going until your inventory is full of obsidian or until it grabs echests

**Comment by Avanatiker** [comment]
Fixed in latest commit please wait for release
