### ISSUE TITLE
weird issue

### ISSUE THREAD

**Issue by FighterJet16** [lambda-plugins/HighwayTools#23]
Whenever building the thing will freak out saying "no netherrack found in inventory" while I'm paving which is odd

**Comment by FighterJet16** [comment]
oh and "no air found in inventory"

**Comment by FighterJet16** [comment]
disable no netherrack in inventory error while in pave mode

**Comment by ReadZead** [comment]
that's the filler block, you have to have netherrack in your inventory or
just do ;ht filler and set the filler block to whatever you want, that's
not a bug, that's intentional
