### ISSUE TITLE
ChestStealer always mode 

### ISSUE THREAD

**Issue by USAFAN** [lambda-plugins/HighwayTools#28]
With always mode on chest stealer it will bounce the last item back and forth between player inventory and chest gui. Using always mode and quickmove under cheststealer.

**Comment by ReadZead** [comment]
this is just for highwaytools plugin related issues, for lambda module issues go here https://github.com/lambda-client/lambda/issues

**Comment by USAFAN** [comment]
wow cant believe i missed that lmao sry
