### ISSUE TITLE
Suggestion: Faster break

### ISSUE THREAD

**Issue by Tokara1** [lambda-plugins/HighwayTools#29]
Faster break Option: that means basically making it possible to break 5-6 netherrack per Tick for Server With lower Packet Limit / mine Limit
( eg Meteor nuker can do that but Its lowkey retarded)

**Comment by Avanatiker** [comment]
if you are using forge 1.12.2 on a 1.12.2 server you can go up to 6 blocks per tick with HWT but its slow with viaforge
