### ISSUE TITLE
1x2 tunnels won't work

### ISSUE THREAD

**Issue by Treeeop** [lambda-plugins/HighwayTools#32]
Hi,

I want to dig a 1x2 tunnel, 1 width and 2 high, but I noticed it seems impossible. It won't make me walk to break the next blocks, even with an autowalk enabled. Doing tests, I noticed that It won't work until I want to do a 3x3 tunnel and higher, below that, I just won't autowalk.

Is it just a setup problem or a bug? Thanks in advance!

**Comment by Avanatiker** [comment]
Iam sorry this is because of the confusing setting CornerBlock
If activated will break the corner in tunnel or place a corner while paving
