### ISSUE TITLE
Can you add support for stacked shulkers of obby

### ISSUE THREAD

**Issue by FighterJet16** [lambda-plugins/HighwayTools#33]
Both 5B and Cloud use this method to build highways
Its annoying to have to use the older kami blue client to use stacked shulks because you can't do it with lambda.
The issue is that it places the shulk takes 1 obby breaks it
can you make it so it takes all the obby and ejects all but 1 stack of the netherrack

**Comment by Avanatiker** [comment]
I added this in latest commit wait for release
