### ISSUE TITLE
Highwaytools issues !25$ XMR reward!

### ISSUE THREAD

**Issue by SavexG** [lambda-plugins/HighwayTools#34]
1.)

main issue is Mining in Highwaytools

when the setting More packets its disabled mining is extremely slow for nearly all blocks as you can see in the following video

timestamps: 
0:00 - 0:11 settings used 
0:12 - 1:02 mining normal blocks
1:03 - .**    mining Obsidian
https://youtu.be/0x3YNJS786o

when the setting More packets is enabled mining Normal blocks such as cobblestone and netherrack works fine but it's unusable for Highway repair because it always gets you kicked on 2b2t when mining obsidian as you can see here:

https://youtu.be/MMG2E08gRUI

2.)

when autoobisidan disables itself as described in this issue https://github.com/lambda-client/lambda/issues/200
Highwaytools tries to mine with it's not properly functioning storage management grinding obisidan thingy even though it's disabled as you can see in this video

https://youtu.be/QfLT3vMgPAo

for any further question or just casual talk about the issues msg Save___G#4444 on discord I can also take some time and explain it again in a screenshare vc

to claim the reward, make a commit that fixes Makes Highwaytools mine all blocks in vanilla speed (or faster) and fix issue 2.) after 1 or 2 days of testing msg Save___G#4444 on discord and you will be rewarded.

Disclamer:
you will get the exchange rate of XMR to $ at the time the transaction will be sent NOT the one from 13.Dec.2021

the cryptocurrency reward is just as a little bonus and shouldn't be seen as a way of compensation for the time and effort put into this
it's a voluntary project.

**Comment by Avanatiker** [comment]
All fixed
