### ISSUE TITLE
Can’t change altitude 

### ISSUE THREAD

**Issue by jaaloley** [lambda-plugins/HighwayTools#40]
If holes in the ground, highway tools stop working because the base of the highway is 119 and not 120. I can’t put all the highways on 120, there are just too many on 119 already.
Sometimes it works though. But I don’t understand why it works sometimes and sometimes not.
Is there a way to say that I want to build on 119?

**Comment by Avanatiker** [comment]
The error message about wrong height is the only thing that changes according to y level. Its just there to alarm people. It does not prevent you to build on other heights.
