### ISSUE TITLE
[BUG] interacting with shulker boxes is broken

### ISSUE THREAD

**Issue by WooHooASDF** [lambda-plugins/HighwayTools#6]
Interacting with shulker boxes to get obsidian is broken on 5b5t

**Comment by Avanatiker** [comment]
Can u further explain or send a clip of it?

**Comment by WooHooASDF** [comment]
It appears to be unable to take the obsiadian out of the shulker box, and it gets stuck in a loop of placing breaking and picking up the shulker box

**Comment by WooHooASDF** [comment]
Nvm, its just getting one stack out at a time.
However, it doesn’t appear to know when to stop grinding obsidian, it filled its inventory and carried on going.

**Comment by Avanatiker** [comment]
It first grinds all obby needed to fill inv and then pick it up. when still doesnt work please send a clip with a new issue
