### ISSUE TITLE
Possible wrong update state used - liquid_flow vs liquid_source

### ISSUE THREAD

**Issue by graemeg** [lambda-plugins/HighwayTools#9]
https://github.com/lambda-plugins/HighwayTools/blob/ae84389ddaf8ff797a7642c8977149049c7ce53d/src/main/kotlin/HighwayTools.kt#L1990

Shouldn't the else block read:
```
it.updateState(TaskState.LIQUID_SOURCE)
```

**Comment by Avanatiker** [comment]
Thanks for the comment didnt see it. I found it myself when refactor to trombone :)
